//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public string UserId { get; set; }
        public string Descripcion { get; set; }
        public string Modulo { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public int CodLog { get; set; }
    }
}
