//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteFichada
    {
        public string Dni { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string FechaNac { get; set; }
        public System.DateTime FechaHoraEntrada { get; set; }
        public Nullable<int> Puntos { get; set; }
        public int CodDisco { get; set; }
    
        public virtual Discoteca Discoteca { get; set; }
    }
}
