//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumicion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consumicion()
        {
            this.Beneficio_has_Consumicion = new HashSet<Beneficio_has_Consumicion>();
            this.Consumicion_Bebida = new HashSet<Consumicion_Bebida>();
            this.DetalleVentaBarras = new HashSet<DetalleVentaBarra>();
            this.ListaPreciosConsumicions = new HashSet<ListaPreciosConsumicion>();
        }
    
        public int DetalleVentaBarraCodConsumicion { get; set; }
        public int Discoteca_CodDiscoteca { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string TerminalAlta { get; set; }
        public string UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public string TerminalMod { get; set; }
        public string UsuarioMod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beneficio_has_Consumicion> Beneficio_has_Consumicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consumicion_Bebida> Consumicion_Bebida { get; set; }
        public virtual Discoteca Discoteca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVentaBarra> DetalleVentaBarras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaPreciosConsumicion> ListaPreciosConsumicions { get; set; }
    }
}
