//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entrada()
        {
            this.DetalleVentaEntradas = new HashSet<DetalleVentaEntrada>();
            this.DetalleVentaEntradas1 = new HashSet<DetalleVentaEntrada>();
            this.PrecioEntradas = new HashSet<PrecioEntrada>();
        }
    
        public int CodEntrada { get; set; }
        public int CodDiscoteca { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Descripcion { get; set; }
        public int CodConsumicion { get; set; }
        public string Estado { get; set; }
    
        public virtual Consumicion Consumicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVentaEntrada> DetalleVentaEntradas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVentaEntrada> DetalleVentaEntradas1 { get; set; }
        public virtual Discoteca Discoteca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrecioEntrada> PrecioEntradas { get; set; }
    }
}
